@Accounting.Endpoints.Api_HostAddress = http://localhost:5289

GET {{Accounting.Endpoints.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
//Correct Request for Journal Entry

POST {{Accounting.Endpoints.Api_HostAddress}}/api/v1/journal
Content-Type: application/json

{
  "date": "2024-01-01",
  "description": "Test Journal",
  "lines": [
    {
      "accountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "debit": 1000,
      "credit": 0
    },
    {
      "accountId": "4fa85f64-5717-4562-b3fc-2c963f66afa6",
      "debit": 0,
      "credit": 1000
    }
  ]
}

###

//Invalid Request for Journal Entry
POST {{Accounting.Endpoints.Api_HostAddress}}/api/v1/journal
Content-Type: application/json

{
  "date": "2024-01-01",
  "description": "",
  "lines": [
    {
      "accountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "debit": 1000,
      "credit": 0
    },
    {
      "accountId": "4fa85f64-5717-4562-b3fc-2c963f66afa6",
      "debit": 0,
      "credit": 1000
    }
  ]
}

###

// Create a New Account
POST {{Accounting.Endpoints.Api_HostAddress}}/api/v1/account
Content-Type: application/json

{
  "code": "1",
  "name": "حساب معین موجودی نقد و بانک",
  "parentId": null,
  "level": 1, 
  "nature": 1,
  "isPostable": true
}

### //ساخت migration
### dotnet ef migrations add InitialCreate -p src/services/accounting/2.infrastructure/data/Accounting.Infrastructure.Data.Sql.Write -s src/services/accounting/3.endpoints/api -c AccountingCommandDbContext
### //اعمال روی دیتابیس
### dotnet ef database update -p src/services/accounting/2.infrastructure/data/Accounting.Infrastructure.Data.Sql.Write -s src/services/accounting/3.endpoints/api -c AccountingCommandDbContext