<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="TngTech.ArchUnitNET" Version="0.13.3" />
    <PackageReference Include="TngTech.ArchUnitNET.xUnit" Version="0.13.3" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\buildingblocks\src\common\BuildingBlocks.Common.csproj" />
    <ProjectReference Include="..\..\accounting\1.core\application\Accounting.Core.Application.csproj" />
    <ProjectReference Include="..\..\accounting\1.core\contracts\Accounting.Core.Contracts.csproj" />
    <ProjectReference Include="..\..\accounting\1.core\domain\Accounting.Core.Domain.csproj" />
    <ProjectReference Include="..\..\accounting\1.core\request-response\Accounting.Core.RequestResponse.csproj" />
    <ProjectReference Include="..\..\accounting\1.core\resources\Accounting.Core.Resources.csproj" />
    <ProjectReference Include="..\..\accounting\2.infrastructure\data\Accounting.Infrastructure.Data.EventSourcing.Write\Accounting.Infrastructure.Data.EventSourcing.Write.csproj" />
    <ProjectReference Include="..\..\accounting\3.endpoints\api\Accounting.Endpoints.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>