<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\common\BuildingBlocks.Common.csproj" />
    <ProjectReference Include="..\..\domain\BuildingBlocks.Domain.csproj" />
  </ItemGroup>

</Project>
