<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\buildingblocks\Integrations\BuildingBlocks.Integration.Marten\BuildingBlocks.Integration.Marten.csproj" />
    <ProjectReference Include="..\domain\Accounting.Core.Domain.csproj" />
  </ItemGroup>

</Project>
